{{- if .Values.ingress.webhook.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chorus.fullname" . }}-webhook
  labels:
    {{- include "chorus.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- if or .Values.ingress.webhook.grpc .Values.ingress.webhook.annotations }}
  annotations:
    {{- if .Values.ingress.webhook.grpc }}
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    {{- end }}
    {{- with .Values.ingress.webhook.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.webhook.className }}
  ingressClassName: {{ .Values.ingress.webhook.className }}
  {{- end }}
  {{- if .Values.ingress.webhook.tls }}
  tls:
    {{- range .Values.ingress.webhook.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.webhook.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if gt (int ($.Values.worker.config.api.webhook.grpcPort | default 0)) 0 }}
                name: {{ include "chorus.fullname" $ }}-webhook
                port:
                  name: {{ if $.Values.ingress.webhook.grpc }}grpc{{ else }}http{{ end }}
                {{- else if $.Values.ingress.webhook.grpc }}
                name: {{ include "chorus.fullname" $ }}-grpc
                port:
                  name: grpc
                {{- else }}
                name: {{ include "chorus.fullname" $ }}-rest
                port:
                  name: rest
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
