apiVersion: v2
name: chorus
description: Helm chart for Chorus S3 management software.
keywords: ["S3","Backup","Replication","Migration"]
home: https://github.com/clyso/chorus
type: application
version: 0.1.2
appVersion: "v0.5.14"
dependencies:
  - name: redis
    version: 17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
